services:
  # local Mongodb service
  mongodb:
    volumes:
      - mongodb:/data/db
    command: mongod --quiet --logpath /dev/null
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    working_dir: /backend
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    working_dir: /frontend
    # restart: unless-stopped
    ports:
      - 8081:8081
    volumes:
      - ./frontend:/frontend

networks:
  default:
    name: my-network
volumes:
  mongodb:
